CREATE TABLE Hospital
(
	Hospital_ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	Name NVARCHAR(150) NOT NULL,
	Type NVARCHAR(50) NULL,
	Bed_Capacity INT NULL,
	Contact_Number VARCHAR(20) NULL,
	Email VARCHAR(100) NULL,
	Address NVARCHAR(260) NULL,
	License_Number VARCHAR(50) NOT NULL,


	-- Constraints

);
GO