CREATE TABLE Nurse
(
	Nurse_ID INT PRIMARY KEY NOT NULL,
	Employee_ID INT NOT NULL UNIQUE,
	Qualification NVARCHAR(100) NOT NULL,
	Shift NVARCHAR(20) NOT NULL,
    CONSTRAINT FK_Nurse_Employee
	FOREIGN KEY (Employee_ID) REFERENCES Employee(Employee_ID)

);