CREATE TABLE Test_Report
(

	Report_ID INT PRIMARY KEY,
	Patient_ID INT NOT NULL,
	Doctor_ID INT NOT NULL,
	Test_Date DATE NOT NULL,
	Test_Type NVARCHAR(100) NOT NULL,
	Result NVARCHAR(1000) NULL,

);